# Generated by Django 2.2.5 on 2019-10-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_status',
            field=models.IntegerField(choices=[(0, 'Drafted'), (1, 'Published')], default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_status',
            field=models.IntegerField(choices=[(0, 'Drafted'), (1, 'Published')], default=0),
        ),
    ]
