# Generated by Django 2.2.5 on 2019-10-09 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191009_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_status',
            field=models.IntegerField(choices=[(0, 'Drafted'), (1, 'Published')], default=1),
        ),
    ]
